name: Go-Jawa Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    ## Setup Postgres
    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Setup Golang-Migrate CLI
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.2/migrate.linux-amd64.tar.gz | tar xvz
        
        ## Get the first file name in the tar.gz
        FILE_NAME=$(tar -tzf migrate.linux-amd64.tar.gz | head -n 1)
        
        ## Extract the file
        tar -xvf migrate.linux-amd64.tar.gz

        ## Move the file to /usr/local/bin
        mv $FILE_NAME /usr/local/bin/migrate

        which migrate

    - name: Run Migration
      run : make migrateup

    - name: Run Test
      run: make test

      
